name: Notify on issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
  
jobs:
  slack-message:
    runs-on: ubuntu-latest

    steps:
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
       notification_title: 'Notification for issue creation'
       footer: 'Linked to Repo <{repo_url}|{repo}>'
        
      env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
       
