name: Notify on issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
  
jobs:
  slack-message:
    runs-on: ubuntu-latest

    steps:
    - name: Report Status
      if: always()
      uses: rtCamp/action-slack-notify@v2
      with:
       notification_title: 'Notification on issue creation'
       footer: '<{repo_url}|{repo}>'
        
      env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_LINK_NAMES: true
       
