name: Notify on issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
  
jobs:
  slack-message:
    runs-on: ubuntu-latest

    steps:
    - name: Slack message on issue creation
      if: always()
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*New issue on REPO: `${{ github.event.repository.name }}`*\n *RUN URL: * <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}> \n> *GITHUB ACTOR:* ${{github.actor}}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        
     
       
